events {}

http {
  map $http_upgrade $connection_upgrade {
    default upgrade;
    "" close;
  }

  upstream main_site {
    server ydl-eap-app:3102;
  }

  upstream pmsys_site {
    server pmsys-app:3000;
  }

  server {
    listen 80 default_server;
    server_name _;
    client_max_body_size 20m;

    location = /pmsys {
      return 308 /pmsys/;
    }

    location /pmsys/assets/ {
      proxy_pass http://pmsys_site/assets/;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /pmsys/ {
      proxy_pass http://pmsys_site;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
    }

    location / {
      proxy_pass http://main_site;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
    }
  }
}
